services:
  mongo:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: exam_backend
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: exam_frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - backend

volumes:
  mongo_data: